apiVersion: "v1"
kind: "Service"
metadata:
  name: "backend-service"
  namespace: "default"
  labels:
    app: "backend"
spec:
  ports:
  - protocol: "TCP"
    port: 5000
  selector:
    app: "backend"
  type: "LoadBalancer"
  loadBalancerIP: ""
