apiVersion: "v1"
kind: "Service"
metadata:
  name: "frontend-service"
  namespace: "default"
  labels:
    app: "frontend"
spec:
  ports:
  - protocol: "TCP"
    port: 3000
  selector:
    app: "frontend"
  type: "LoadBalancer"
  loadBalancerIP: ""
